name: "Ansible Deployment"

on:
  push:
    branches:
      - prod
    paths:
      - 'prod/**'

  pull_request:
    branches:
      - prod
    paths:
      - 'prod/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  ansible:
    name: "Run Ansible Playbook"
    runs-on: ubuntu-latest
    environment: prod
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      VOC_KEY: ${{ secrets.VOC_KEY }}
      ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Ansible
        run: |
         sudo apt update
         sudo apt install software-properties-common
         sudo add-apt-repository --yes --update ppa:ansible/ansible
         sudo apt-get install ansible -y
      
      - name: Install boto3 and botocore for Ansible
        run: |
         /opt/pipx/venvs/ansible-core/bin/python -m pip install boto3 botocore
      
      - name: setup ssh private key
        working-directory: ./key_pairs
        run: |
         echo "${{ secrets.VOC_KEY }}" > private_key.pem
         sudo chmod 600 private_key.pem
        

      - name: Output Ansible Results to PR
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'  # Only run this for PR events
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require("fs");
            const output = fs.readFileSync("/tmp/ansible_output.txt", "utf8");
            const maxGitHubBodyCharacters = 65536;  # Maximum size for GitHub comments

            // Function to split output into smaller chunks if it's too large
            function chunkSubstr(str, size) {
              const numChunks = Math.ceil(str.length / size);
              const chunks = new Array(numChunks);
              for (let i = 0, o = 0; i < numChunks; ++i, o += size) {
                chunks[i] = str.substr(o, size);
              }
              return chunks;
            }

            var outputChunks = chunkSubstr(output, maxGitHubBodyCharacters);  // Split if needed
            for (let i = 0; i < outputChunks.length; i++) {
              const comment = `### Ansible Playbook Output - Part ${i + 1}
              <details><summary>Show Output</summary>
              \`\`\`
              ${outputChunks[i]}
              \`\`\`
              </details>`;
              
              // Post the comment on the PR
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }

      # Apply changes (this step can be adjusted for your needs)
      - name: Apply Ansible Changes
        if: github.ref == 'refs/heads/prod' && github.event_name == 'push'
        run: |
          ansible-playbook -i ../aws_ec2.yaml prod_playbook.yml --private-key ../key_pairs/private_key.pem -u ${{ secrets.ANSIBLE_USER }} -e 'ansible_ssh_common_args="-o StrictHostKeyChecking=no"'
        shell: bash
        working-directory: ./prod
